name: Auto-release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  create_assets:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ifrit-AI/requirements.txt
          pip install pyinstaller
          python --version
          pip freeze
      - uses: milliewalky/setup-7-zip@v1
      - name: Create xlsx release
        shell: bash
        run: |
          cd ifrit-xlsx/
          pyinstaller -n ifrit-xlsx -F --specpath release/build --distpath release --workpath release/build  main.py
          cp -r Resources/ release/
          rm -rf OriginalFiles/decompressed_battle 
          mkdir -p release/OriginalFiles/
          cp OriginalFiles/en_battle/battle.* release/OriginalFiles
          rm -r release/build
          cd ..
      - name: Create ai release
        shell: bash
        run: |
          cd ifrit-AI/
          pyinstaller -n ifrit-ai -F --specpath release/build --distpath release --workpath release/build --onefile --noconsole --icon=../../Resources/icon.ico main.py
          mkdir -p release/OriginalFiles/
          cp -r Resources/ release/
          cp -r OriginalFiles/ release/
          rm -r release/build
          ls -al
          cd ..
      - name: Create full release - Start
        shell: bash
        run: |
          mkdir -p release/ifrit-enhanced
          mkdir -p release/ifrit-enhanced/ifrit-gui
          mkdir -p release/ifrit-enhanced/ifrit-ai
          mkdir -p release/ifrit-enhanced/ifrit-xlsx
          cp -R ifrit-ai/release/* release/ifrit-enhanced/ifrit-ai/
          cp -R ifrit-xlsx/release/* release/ifrit-enhanced/ifrit-xlsx/
          cp -R ifrit-gui/publish/* release/ifrit-enhanced/ifrit-gui/
          rm -rf ifrit-ai/release
          rm -rf ifrit-xlsx/release
          cd release/ifrit-enhanced
      - name: zip name continuous
        if: github.event.ref_type != 'tag' && github.ref == 'refs/heads/master'
        run: 7z  a -tzip ../ifrit-enhanced-continuous.zip .
      - name: zip name tag
        if: github.event.ref_type == 'tag'
        run: 7z  a -tzip ../ifrit-enhanced${{  github.ref_name }}.zip .  
      - name: Create full release - End
        shell: bash
        run: |
          cd ..
          rm -r ifrit-enhanced
          cd ..
          ls -al
          ls -al release/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "artifact-${{ github.sha }}"
          path: ${{ github.workspace }}/release/*
  release_assets:
    name: Release
    needs:
    - create_assets
    runs-on: windows-latest
    concurrency: release-${{ github.ref }}
    steps:
    - name: Download Files
      uses: actions/download-artifact@v4
    - name: Test
      shell: bash
      run: |
        ls -al
    - name: Deploy Package
      if: github.event.ref_type != 'tag' && github.ref == 'refs/heads/master'
      uses: crowbarmaster/GH-Automatic-Releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Unstable Build"
        files: |
          artifact-*/*
    - name: Deploy Package
      if: github.event.ref_type == 'tag'
      uses: crowbarmaster/GH-Automatic-Releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        title: ${{ github.event.ref }}
        files: |
          artifact-*/*
