name: Auto-release

on:
  push:
    branches: [ "master" ]
    tags:
      - "*"
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  release-version:
      runs-on: windows-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: recursive submodule
        shell: bash
        run: |
          git submodule update --init --recursive
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r FF8GameData/requirements.txt
          pip install -r requirements.txt
          pip install pyinstaller
          pip freeze
      - uses: milliewalky/setup-7-zip@v1
      - name: Create patcher
        shell: bash
        run: |
          mkdir -p Patcher
          pyinstaller -n Patcher -F --specpath release/build --distpath release/Patcher --noconsole --workpath release/build --onefile --icon=../../Resources/hobbitdur.ico Patcher/main.py
          rm -R release/build
          cd release
          ls -al
          cd ..
      - name: Create release
        shell: bash
        run: |
          pyinstaller -n FF8UltimateEditor -F --specpath release/build --distpath release --noconsole --workpath release/build --onefile --icon=../../Resources/hobbitdur.ico main.py
          mkdir -p release/Resources
          mkdir -p release/Junkshop
          mkdir -p release/Quezacotl
          mkdir -p release/Doomtrain
          mkdir -p release/JumboCactuar
          mkdir -p release/IfritGui
          mkdir -p release/Siren
          mkdir -p release/Deling
          mkdir -p release/FF8GameData
          mkdir -p release/FF8GameData/Resources
          mkdir -p release/FF8GameData/fs
          mkdir -p release/FF8GameData/fs/DelingCli
          mkdir -p release/ToolUpdate
          mkdir -p release/ShumiTranslator
          mkdir -p release/ShumiTranslator/csv
          cp -R ShumiTranslator/csv/. release/ShumiTranslator/csv
          cp ToolUpdate/list.json release/ToolUpdate/
          cp -R FF8GameData/Resources/. release/FF8GameData/Resources/
          cp -R Resources/. release/Resources/
          rm -R release/build
          cd release
          ls -al
          cd ..
      - name: zip name continuous
        shell: bash
        if: github.event.ref_type != 'tag' && github.ref == 'refs/heads/master'
        run: |
          cd release
          7z  a -tzip "FF8UltimateEditor-continuous-${{ github.sha}}.zip" .
          pwd
          cd ..
          ls -al
      - name: zip name tag
        shell: bash
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd release
          7z  a -tzip "FF8UltimateEditor-${{  github.ref_name }}.zip" .
          cd ..
      - name: Deploy Package
        if: github.event.ref_type != 'tag' && github.ref == 'refs/heads/master'
        uses: crowbarmaster/GH-Automatic-Releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "continuous"
          prerelease: true
          title: "Unstable Build"
          files: |
            release/FF8UltimateEditor-*.zip
      - name: Deploy tag Package
        if:  startsWith(github.ref, 'refs/tags/')
        uses: crowbarmaster/GH-Automatic-Releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{ github.ref_name }}
          title: "FF8UltimateEditor-${{ github.ref_name }}"
          files: |
            release/FF8UltimateEditor-*.zip
